services:
    nginx:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./certs:/etc/letsencrypt/
      restart: unless-stopped
      env_file: docker.env

    web:
      image: python:3.11
      command: python -m http.server 8000